# Generated by Django 4.0.4 on 2022-05-16 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('idRaza', models.AutoField(primary_key=True, serialize=False, verbose_name='Código de la Raza')),
                ('nombre', models.CharField(max_length=30, null=True, verbose_name='Nombre de la Raza')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('chip', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código chip de la Mascota')),
                ('nombreMascota', models.CharField(max_length=50, verbose_name='Nombre de la Mascota')),
                ('edadMascota', models.IntegerField(verbose_name='Edad de la mascota')),
                ('colorPelo', models.CharField(max_length=30, verbose_name='Color de cabello de la mascota')),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventas.raza')),
            ],
        ),
    ]
